### ISSUE TITLE
Error while WorkArena-install 

### ISSUE THREAD

**Issue by dgjun32** [ServiceNow/WorkArena#21]
While I setup the install the WorkArena after setting up the SNOW instance, 
I am facing with following error.

```
INFO:root:All fields properly displayed for /now/nav/ui/classic/params/target/change_request.do.
INFO:root:Setting up form fields for create_incident...
Traceback (most recent call last):
  File "/home/dongjun/anaconda3/envs/webarena/bin/workarena-install", line 8, in <module>
    sys.exit(main())
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/browsergym/workarena/install.py", line 1014, in main
    setup()
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/tenacity/__init__.py", line 330, in wrapped_f
    return self(f, *args, **kw)
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/tenacity/__init__.py", line 467, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/tenacity/__init__.py", line 410, in exc_check
    raise retry_exc.reraise()
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/tenacity/__init__.py", line 183, in reraise
    raise self.last_attempt.result()
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/tenacity/__init__.py", line 470, in __call__
    result = fn(*args, **kwargs)
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/browsergym/workarena/install.py", line 977, in setup
    setup_form_fields()
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/browsergym/workarena/install.py", line 696, in setup_form_fields
    process_form_fields(
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/tenacity/__init__.py", line 330, in wrapped_f
    return self(f, *args, **kw)
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/tenacity/__init__.py", line 467, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/tenacity/__init__.py", line 390, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/tenacity/__init__.py", line 470, in __call__
    result = fn(*args, **kwargs)
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/browsergym/workarena/install.py", line 620, in process_form_fields
    page.wait_for_function("typeof gsft_main.GlideList2 !== 'undefined'")
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 11820, in wait_for_function
    self._sync(
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/playwright/_impl/_page.py", line 957, in wait_for_function
    return await self._main_frame.wait_for_function(**locals_to_params(locals()))
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 763, in wait_for_function
    return from_channel(await self._channel.send("waitForFunction", params))
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 461, in wrap_api_call
    return await cb()
  File "/home/dongjun/anaconda3/envs/webarena/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
```

I am using conda environment with python 3.10 now.

**Comment by aldro61** [comment]
Hello! This might be due to some networking issues we encountered last week. Could you please try again? A few of us ran the setup script on a fresh instance today, and everything worked fine.

**Comment by dgjun32** [comment]
Do I have to release previous instance and setup new instance?
With my previous instance, I again encountered the following error.

```
INFO:root:Setting up form fields for create_hardware...                                                                                                                                                                                                                                                                    
INFO:root:Checking for new user preferences for create_hardware form fields                                                                                                                                                                                                                                                
INFO:root:Validating form fields for create_hardware...                                                                                                                                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                                                                                                                                                         
  File "/home/dongjun/anaconda3/envs/workarena/bin/workarena-install", line 8, in <module>                                                                                                                                                                                                                                 
    sys.exit(main())                                                                                                                                                                                                                                                                                                       
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/browsergym/workarena/install.py", line 1075, in main                                                                                                                                                                                           
    setup()                                                                                                                                                                                                                                                                                                                
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/tenacity/__init__.py", line 336, in wrapped_f                                                                                                                                                                                                  
    return copy(f, *args, **kw)                                                                                                                                                                                                                                                                                            
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/tenacity/__init__.py", line 475, in __call__                                                                                                                                                                                                   
    do = self.iter(retry_state=retry_state)                                                                                                                                                                                                                                                                                
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/tenacity/__init__.py", line 376, in iter                                                                                                                                                                                                       
    result = action(retry_state)                                                                                                                                                                                                                                                                                           
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/tenacity/__init__.py", line 418, in exc_check                                                                                                                                                                                                  
    raise retry_exc.reraise()                                                                                                                                                                                                                                                                                              
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/tenacity/__init__.py", line 185, in reraise                                                                                                                                                                                                    
    raise self.last_attempt.result()                                                                                                                                                                                                                                                                                       
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/concurrent/futures/_base.py", line 438, in result                                                                                                                                                                                                            
    return self.__get_result()                                                                                                                                                                                                                                                                                             
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result                                                                                                                                                                                                      
    raise self._exception                                                                                                                                                                                                                                                                                                  
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/tenacity/__init__.py", line 478, in __call__                                                                                                                                                                                                   
    result = fn(*args, **kwargs)                                                                                                                                                                                                                                                                                           
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/browsergym/workarena/install.py", line 1038, in setup                                                                                                                                                                                          
    setup_form_fields()                                                                                                                                                                                                                                                                                                    
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/browsergym/workarena/install.py", line 762, in setup_form_fields                                                                                                                                                                               
    assert process_form_fields(                                                                                                                                                                                                                                                                                            
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/tenacity/__init__.py", line 336, in wrapped_f                                                                                                                                                                                                  
    return copy(f, *args, **kw)                                                                                                                                                                                                                                                                                            
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/tenacity/__init__.py", line 475, in __call__                                                                                                                                                                                                   
    do = self.iter(retry_state=retry_state)                                                                                                                                                                                                                                                                                
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/tenacity/__init__.py", line 376, in iter                                         
    result = action(retry_state)                                                                                                                                                                                                                                                                                           
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/tenacity/__init__.py", line 398, in <lambda>                                                                                                                                                                                                   
    self._add_action_func(lambda rs: rs.outcome.result())                                                                                                    
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/concurrent/futures/_base.py", line 438, in result                                              
    return self.__get_result()                                                                                                                                                                                                                                                                                             
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result                                                                                                                                                                                                      
    raise self._exception                                                                                                                                    
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/tenacity/__init__.py", line 478, in __call__                                     
    result = fn(*args, **kwargs)                                                                                                                             
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/browsergym/workarena/install.py", line 646, in process_form_fields               
    page = browser.new_page()                                                                                                                                
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 14487, in new_page                                                                                                                                                                                    
    self._sync(                                                                                                                                                                                                                                                                                                            
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync                              
    return task.result()                                                                                                                                     
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/playwright/_impl/_browser.py", line 180, in new_page                             
    return await self._connection.wrap_api_call(inner)                                                                                                       
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 490, in wrap_api_call                     
    return await cb()                                                                                                                                        
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/playwright/_impl/_browser.py", line 175, in inner                                
    page = await context.new_page()                                                                                                                          
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/playwright/_impl/_browser_context.py", line 281, in new_page                     
    return from_channel(await self._channel.send("newPage"))                                                                                                 
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(                                                                                                             
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 485, in wrap_api_call                     
    return await cb()                                                                                                                                                                                                                                                                                                      
  File "/home/dongjun/anaconda3/envs/workarena/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 99, in inner_send                                                                                                                                                                                       
    result = next(iter(done)).result()                                                                                                                       
playwright._impl._api_types.Error: Page closed 
```

**Comment by aldro61** [comment]
Yes, please try to:
* Release your instance
* Wait a few minutes until you can request a new one
* Request a "Washington" version instance
* Try running the installer again.

Let me know if this solves it. Thanks for your time.

**Comment by dgjun32** [comment]
The problem was resolved! Thanks very much.
