### ISSUE TITLE
Error in workarena-install

### ISSUE THREAD

**Issue by aviyaeli** [ServiceNow/WorkArena#24]
I'm following the instructions to install workarena.  
I've created an account on ServiceNow and set the environment variables

When runnign `workarena-install`, I'm receiving the error below.
I'm running Python 3.11.5 on MacOS 14.3.1 
```
INFO:root:

██     ██  ██████  ██████  ██   ██  █████  ██████  ███████ ███    ██  █████
██     ██ ██    ██ ██   ██ ██  ██  ██   ██ ██   ██ ██      ████   ██ ██   ██
██  █  ██ ██    ██ ██████  █████   ███████ ██████  █████   ██ ██  ██ ███████
██ ███ ██ ██    ██ ██   ██ ██  ██  ██   ██ ██   ██ ██      ██  ██ ██ ██   ██
 ███ ███   ██████  ██   ██ ██   ██ ██   ██ ██   ██ ███████ ██   ████ ██   ██

Instance: https://dev265136.service-now.com
Previous installation: never


INFO:root:URL login enabled.
INFO:root:Setting default home page
INFO:root:Guided tours disabled.
INFO:root:Analytics popups disabled.
INFO:root:Welcome help popup disabled.
INFO:root:Installing custom UI themes...
INFO:root:Uploading update set...
INFO:root:Applying update set...
INFO:root:An error occurred. Retrying...
INFO:root:URL login enabled.
INFO:root:Setting default home page
INFO:root:Guided tours disabled.
INFO:root:Analytics popups disabled.
INFO:root:Welcome help popup disabled.
INFO:root:Installing custom UI themes...
INFO:root:Uploading update set...
INFO:root:Applying update set...
INFO:root:An error occurred. Retrying...
INFO:root:URL login enabled.
INFO:root:Setting default home page
INFO:root:Guided tours disabled.
INFO:root:Analytics popups disabled.
INFO:root:Welcome help popup disabled.
INFO:root:Installing custom UI themes...
INFO:root:Uploading update set...
INFO:root:Applying update set...
Traceback (most recent call last):
  File "/Users/aviy/.local/share/virtualenvs/BrowserGym-epKWcu_M/bin/workarena-install", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/aviy/.local/share/virtualenvs/BrowserGym-epKWcu_M/lib/python3.11/site-packages/browsergym/workarena/install.py", line 1075, in main
    setup()
  File "/Users/aviy/.local/share/virtualenvs/BrowserGym-epKWcu_M/lib/python3.11/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/aviy/.local/share/virtualenvs/BrowserGym-epKWcu_M/lib/python3.11/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aviy/.local/share/virtualenvs/BrowserGym-epKWcu_M/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/aviy/.local/share/virtualenvs/BrowserGym-epKWcu_M/lib/python3.11/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/aviy/.local/share/virtualenvs/BrowserGym-epKWcu_M/lib/python3.11/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/aviy/.local/share/virtualenvs/BrowserGym-epKWcu_M/lib/python3.11/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/aviy/.local/share/virtualenvs/BrowserGym-epKWcu_M/lib/python3.11/site-packages/browsergym/workarena/install.py", line 1025, in setup
    setup_ui_themes()
  File "/Users/aviy/.local/share/virtualenvs/BrowserGym-epKWcu_M/lib/python3.11/site-packages/browsergym/workarena/install.py", line 837, in setup_ui_themes
    _install_update_set(path=UI_THEMES_UPDATE_SET["update_set"], name=UI_THEMES_UPDATE_SET["name"])
  File "/Users/aviy/.local/share/virtualenvs/BrowserGym-epKWcu_M/lib/python3.11/site-packages/browsergym/workarena/install.py", line 138, in _install_update_set
    update_set = table_api_call(
                 ^^^^^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by dolev31** [comment]
This should be added: 
export SNOW_INSTANCE_USER="admin"

For some reason, the Readme refers to SNOW_INSTANCE_UNAME, which is incorrect.

**Comment by aviyaeli** [comment]
@dolev31 solved my problem.  Thanks !

Suggest you change the README

**Comment by aldro61** [comment]
@aviyaeli I'm glad your issue is solved. Let us know if you run into anything else.

@dolev31 thanks very much for helping out! Could you please clarify why you mention `SNOW_INSTANCE_USER`? I double-checked the code and I can't find any usage of it. The instance.py code uses `SNOW_INSTANCE_UNAME`. Thanks!

**Comment by aviyaeli** [comment]
@aldro61 strange indeed. I also searched the code and don't see SNOW_INSTANCE_USER.  Maybe just the removal of the SNOW_INSTANCE_UNAME from my env is what solved the problem.

**Comment by aldro61** [comment]
This is very strange since the code would crash if _UNAME was not set (see https://github.com/ServiceNow/WorkArena/blob/workarena-plus-plus/src/browsergym/workarena/instance.py#L46). 

I'm glad it's working now. I will close the issue but won't update the readme since the _USER variable is not the correct variable name. 

Please let me know if you encounter any other issues in the future. 

Thanks!
