### ISSUE TITLE
Error in workarena-install. And cannot select Washington DC release.

### ISSUE THREAD

**Issue by minghchen** [ServiceNow/WorkArena#38]
workarena-install
```
INFO:root:

██     ██  ██████  ██████  ██   ██  █████  ██████  ███████ ███    ██  █████
██     ██ ██    ██ ██   ██ ██  ██  ██   ██ ██   ██ ██      ████   ██ ██   ██
██  █  ██ ██    ██ ██████  █████   ███████ ██████  █████   ██ ██  ██ ███████
██ ███ ██ ██    ██ ██   ██ ██  ██  ██   ██ ██   ██ ██      ██  ██ ██ ██   ██
 ███ ███   ██████  ██   ██ ██   ██ ██   ██ ██   ██ ███████ ██   ████ ██   ██

Instance: https://dev287879.service-now.com
Previous installation: never


INFO:root:An error occurred. Retrying...
INFO:root:An error occurred. Retrying...
Traceback (most recent call last):
  File "/Users/macair/miniconda3/envs/py310/bin/workarena-install", line 8, in <module>
    sys.exit(main())
  File "/Users/macair/miniconda3/envs/py310/lib/python3.10/site-packages/browsergym/workarena/install.py", line 1075, in main
    setup()
  File "/Users/macair/miniconda3/envs/py310/lib/python3.10/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
  File "/Users/macair/miniconda3/envs/py310/lib/python3.10/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/macair/miniconda3/envs/py310/lib/python3.10/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/Users/macair/miniconda3/envs/py310/lib/python3.10/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/Users/macair/miniconda3/envs/py310/lib/python3.10/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/Users/macair/miniconda3/envs/py310/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/macair/miniconda3/envs/py310/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/macair/miniconda3/envs/py310/lib/python3.10/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
  File "/Users/macair/miniconda3/envs/py310/lib/python3.10/site-packages/browsergym/workarena/install.py", line 1007, in setup
    if not check_instance_release_support():
  File "/Users/macair/miniconda3/envs/py310/lib/python3.10/site-packages/browsergym/workarena/install.py", line 784, in check_instance_release_support
    if version_info["build name"] not in SNOW_SUPPORTED_RELEASES:
KeyError: 'build name'
```
python version: 3.10.14

On servicenow, I can only select 'Xanadu' release:
<img width="618" alt="截屏2024-10-16 17 09 57" src="https://github.com/user-attachments/assets/30107b47-8911-444f-a34b-8766965b13eb">

**Comment by aldro61** [comment]
@minghchen just saw the title that mentions you cannot select a Washington instance. Can you please clarify why?

**Comment by aldro61** [comment]
Closing this due to inactivity but please make sure you select a Washington instance. There might be short waitlist in times of high demand.
