### ISSUE TITLE
Fail to workarena-install.

### ISSUE THREAD

**Issue by Iriseve** [ServiceNow/WorkArena#5]
I have properly logged in to servicenow and obtained an instance, but when I correctly configured the environment variable and executed `workarena-install` command to upload benchmark data, I encountered the following error
~~~
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for get_by_label("Available", exact=True)
  locator resolved to <select size="10" width="120" multiple="yes" id="slush_l…>…</select>
  selecting specified option(s)
    did not find some options - waiting...
============================================================

~~~
 which appears to be due to connection timeout, but I configured it in a local windows environment and enabled the proxy. Is there any way to solve this problem?

The complete information is below:
~~~
INFO:root:All workflows are installed properly.
INFO:root:Knowledge base is already installed.
INFO:root:All columns properly displayed for /now/nav/ui/classic/params/target/alm_asset_list.do%3Fsysparm_view%3Ditam_workspace%26sysparm_userpref.alm_asset_list.view%3Ditam_workspace%26sysparm_userpref.alm_asset.view%3Ditam_workspace%26sysparm_query%3D%26sysparm_fixed_query%3D.
INFO:root:All columns properly displayed for /now/nav/ui/classic/params/target/alm_hardware_list.do%3Fsysparm_view%3Ditam_workspace%26sysparm_userpref.alm_hardware_list.view%3Ditam_workspace%26sysparm_userpref.alm_hardware.view%3Ditam_workspace%3D%26sysparm_query%3Dinstall_status%253D6%255Esubstatus%253Dpre_allocated.
INFO:root:All columns properly displayed for /now/nav/ui/classic/params/target/change_request_list.do%3Fsysparm_view%3Dsow%26sysparm_userpref.change_request_list.view%3Dsow%26sysparm_userpref.change_request.view%3Dsow%26sysparm_query%3D%26sysparm_fixed_query%3D.
INFO:root:All columns properly displayed for /now/nav/ui/classic/params/target/incident_list.do%3Fsysparm_query%3Dactive%253Dtrue%26sysparm_first_row%3D1%26sysparm_view%3DMajor%2520Incidents.
Traceback (most recent call last):
  File "E:\anaconda3\envs\pytorch\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\anaconda3\envs\pytorch\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\anaconda3\envs\pytorch\Scripts\workarena-install.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "E:\anaconda3\envs\pytorch\lib\site-packages\browsergym\workarena\install.py", line 549, in main
    setup()
  File "E:\anaconda3\envs\pytorch\lib\site-packages\browsergym\workarena\install.py", line 539, in setup
    setup_list_columns()
  File "E:\anaconda3\envs\pytorch\lib\site-packages\browsergym\workarena\install.py", line 407, in setup_list_columns
    display_all_expected_columns(task_info["url"], expected_columns=expected_columns)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
  File "E:\anaconda3\envs\pytorch\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "E:\anaconda3\envs\pytorch\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "E:\anaconda3\envs\pytorch\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\browsergym\workarena\install.py", line 340, in display_all_expected_columns
    available_columns.select_option(value=columns_to_add)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\playwright\sync_api\_generated.py", line 17349, in select_option
    self._sync(
  File "E:\anaconda3\envs\pytorch\lib\site-packages\playwright\_impl\_sync_base.py", line 104, in _sync
    return task.result()
  File "E:\anaconda3\envs\pytorch\lib\site-packages\playwright\_impl\_locator.py", line 515, in select_option
    return await self._frame.select_option(
  File "E:\anaconda3\envs\pytorch\lib\site-packages\playwright\_impl\_frame.py", line 671, in select_option
    return await self._channel.send("selectOption", params)
  File "E:\anaconda3\envs\pytorch\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "E:\anaconda3\envs\pytorch\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "E:\anaconda3\envs\pytorch\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for get_by_label("Available", exact=True)
  locator resolved to <select size="10" width="120" multiple="yes" id="slush_l…>…</select>
  selecting specified option(s)
    did not find some options - waiting...
============================================================
~~~

**Comment by aldro61** [comment]
Hello! Thanks for your interest in our work. This has been fixed in a newer version of the code. I believe the playwright code is waiting for a control that is not on the page. We expect to update the code in this repo in the coming week. Will ping you once this is done.

**Comment by Iriseve** [comment]
> Hello! Thanks for your interest in our work. This has been fixed in a newer version of the code. I believe the playwright code is waiting for a control that is not on the page. We expect to update the code in this repo in the coming week. Will ping you once this is done.

Thanks very much!

**Comment by aldro61** [comment]
@Iriseve could you please let us know if your issue is solved now? Thank you!

**Comment by Iriseve** [comment]
That's fine now. Thank you so much!
