### ISSUE TITLE
Error in workarena-install

### ISSUE THREAD

**Issue by dangne** [ServiceNow/WorkArena#50]
Hi, I am having trouble at the `workarena-install` step. Below is the traceback:
```
Instance: https://dev257112.service-now.com
Previous installation: never


INFO:root:An error occurred. Retrying...
INFO:root:An error occurred. Retrying...
Traceback (most recent call last):
  File "/Users/dang/.local/bin/workarena-install", line 8, in <module>
    sys.exit(main())
  File "/Users/dang/.local/lib/python3.10/site-packages/browsergym/workarena/install.py", line 1075, in main
    setup()
  File "/Users/dang/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
  File "/Users/dang/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/dang/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/Users/dang/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/Users/dang/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/Users/dang/miniconda3/envs/hero/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/dang/miniconda3/envs/hero/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/dang/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
  File "/Users/dang/.local/lib/python3.10/site-packages/browsergym/workarena/install.py", line 1007, in setup
    if not check_instance_release_support():
  File "/Users/dang/.local/lib/python3.10/site-packages/browsergym/workarena/install.py", line 783, in check_instance_release_support
    version_info = instance.release_version
  File "/Users/dang/.local/lib/python3.10/site-packages/browsergym/workarena/instance.py", line 113, in release_version
    ui_login(self, page)
  File "/Users/dang/.local/lib/python3.10/site-packages/browsergym/workarena/utils.py", line 58, in ui_login
    page.goto(instance.snow_url)
  File "/Users/dang/.local/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 9303, in goto
    self._sync(
  File "/Users/dang/.local/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
  File "/Users/dang/.local/lib/python3.10/site-packages/playwright/_impl/_page.py", line 473, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/Users/dang/.local/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 138, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/Users/dang/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/Users/dang/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 490, in wrap_api_call
    return await cb()
  File "/Users/dang/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 99, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Page closed
=========================== logs ===========================
navigating to "https://dev257112.service-now.com/", waiting until "load"
============================================================
```

Thanks so much for you help!

**Comment by aldro61** [comment]
Hi! Please share your credentials by email and I will try to understand: alexandre.drouin@servicenow.com.

**Comment by aldro61** [comment]
Thanks for the credentials. I'm currently running the installer on your instance. It appears to be a bit slower than usual, but it appears to be working.
![image](https://github.com/user-attachments/assets/d94d8cd5-7b83-404e-85a6-05313dd93200)

I will let it run and let you know when it completes.

**Comment by aldro61** [comment]
<img width="311" alt="image" src="https://github.com/user-attachments/assets/a19a019e-0042-4b91-895c-7e22a79b9822">

Your instance is fully set up now; there is no need to re-run on your side. I'm not sure what went wrong. It could have been network issues on your end or a temporary glitch at our data center.

Please re-open if you run into any issues while benchmarking.

**Comment by dangne** [comment]
Thank you for your help. I'm trying to run the following example script from the README file:
```
import random

from browsergym.core.env import BrowserEnv
from browsergym.workarena import ALL_WORKARENA_TASKS
from time import sleep


random.shuffle(ALL_WORKARENA_TASKS)
for task in ALL_WORKARENA_TASKS:
    print("Task:", task)

    # Instantiate a new environment
    env = BrowserEnv(task_entrypoint=task,
                    headless=False)
    env.reset()

    # Cheat functions use Playwright to automatically solve the task
    env.chat.add_message(role="assistant", msg="On it. Please wait...")
    cheat_messages = []
    env.task.cheat(env.page, cheat_messages)

    # Send cheat messages to chat
    for cheat_msg in cheat_messages:
        env.chat.add_message(role=cheat_msg["role"], msg=cheat_msg["message"])

    # Post solution to chat
    env.chat.add_message(role="assistant", msg="I'm done!")

    # Validate the solution
    reward, stop, message, info = env.task.validate(env.page, cheat_messages)
    if reward == 1:
        env.chat.add_message(role="user", msg="Yes, that works. Thanks!")
    else:
        env.chat.add_message(role="user", msg=f"No, that doesn't work. {info.get('message', '')}")

    sleep(3)
    env.close()
```

But I got a similar error message as above (with different traceback):
```
Task: <class 'browsergym.workarena.tasks.compositional.DashboardRetrieveIncidentAndMeanRequestGoogleNexus7TaskL2'>
Traceback (most recent call last):
  File "/Users/dang/projects/hero/try_workarena.py", line 15, in <module>
    env.reset()
  File "/Users/dang/.local/lib/python3.11/site-packages/browsergym/core/env.py", line 281, in reset
    self.chat = Chat(
                ^^^^^
  File "/Users/dang/.local/lib/python3.11/site-packages/browsergym/core/chat.py", line 35, in __init__
    self.page = self.context.new_page()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dang/.local/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 13095, in new_page
    return mapping.from_impl(self._sync(self._impl_obj.new_page()))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dang/.local/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/Users/dang/.local/lib/python3.11/site-packages/playwright/_impl/_browser_context.py", line 281, in new_page
    return from_channel(await self._channel.send("newPage"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dang/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dang/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 490, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/Users/dang/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 99, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: Page closed
```

**Comment by aldro61** [comment]
This is very strange. It seems to be an issue with your playwright installation. Could you tell me more about your setup?

Is this a remote server? Did you run `playwright install`? Anything else you think might help.

@gasse does this issue ring a bell?

**Comment by aldro61** [comment]
@dangne I can't reproduce your issue on my end. However, I'm running into other issues later in the demo. I will address these ASAP. cc @jardinetsouffleton

**Comment by dangne** [comment]
Okay, I fixed the problem by updating playwright to the latest version with `pip install -U playwright` and run `playwright install` again.

**Comment by aldro61** [comment]
Can you give this demo script a shot please?

```python
import random

from browsergym.core.env import BrowserEnv
from browsergym.workarena import ALL_WORKARENA_TASKS
from browsergym.workarena.tasks.compositional.base import CompositionalTask
from time import sleep


random.shuffle(ALL_WORKARENA_TASKS)
for task in ALL_WORKARENA_TASKS:
    print("Task:", task)

    # Instantiate a new environment
    env = BrowserEnv(task_entrypoint=task,
                    headless=False)
    env.reset()

    # Cheat functions use Playwright to automatically solve the task
    env.chat.add_message(role="assistant", msg="On it. Please wait...")
    cheat_messages = []
    if isinstance(env.task, CompositionalTask):
        # Need to cheat for all subtasks
        for i in range(len(env.task.subtasks)):
            env.task.cheat(env.page, cheat_messages, i)
    else:
        env.task.cheat(env.page, cheat_messages)

    # Send cheat messages to chat
    for cheat_msg in cheat_messages:
        env.chat.add_message(role=cheat_msg["role"], msg=cheat_msg["message"])

    # Post solution to chat
    env.chat.add_message(role="assistant", msg="I'm done!")

    # Validate the solution
    reward, stop, message, info = env.task.validate(env.page, cheat_messages)
    if reward == 1:
        env.chat.add_message(role="user", msg="Yes, that works. Thanks!")
    else:
        env.chat.add_message(role="user", msg=f"No, that doesn't work. {info.get('message', '')}")

    sleep(3)
    env.close()
```

**Comment by dangne** [comment]
Yes, it's (kinda) work. The browser and chat windows appear normally but now I got timeout errors at the `env.task.cheat(env.page, cheat_messages, i)` step for every task.
```
Task: <class 'browsergym.workarena.tasks.compositional.TwoChangesFixBasicVariedRiskChangeRequestSchedulingTaskL3'>
Traceback (most recent call last):
  File "/Users/dang/projects/hero/try_workarena.py", line 76, in <module>
    env.task.cheat(env.page, cheat_messages, i)
  File "/Users/dang/miniconda3/envs/hero/lib/python3.11/site-packages/browsergym/workarena/tasks/compositional/base.py", line 198, in cheat
    self.subtasks[subtask_idx].cheat(page, chat_messages)
  File "/Users/dang/miniconda3/envs/hero/lib/python3.11/site-packages/browsergym/workarena/tasks/list.py", line 667, in cheat
    self._wait_for_ready(page)
  File "/Users/dang/miniconda3/envs/hero/lib/python3.11/site-packages/browsergym/workarena/tasks/list.py", line 189, in _wait_for_ready
    page.wait_for_function(
  File "/Users/dang/miniconda3/envs/hero/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 11537, in wait_for_function
    self._sync(
  File "/Users/dang/miniconda3/envs/hero/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/Users/dang/miniconda3/envs/hero/lib/python3.11/site-packages/playwright/_impl/_page.py", line 1083, in wait_for_function
    return await self._main_frame.wait_for_function(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dang/miniconda3/envs/hero/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 771, in wait_for_function
    return from_channel(await self._channel.send("waitForFunction", params))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dang/miniconda3/envs/hero/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dang/miniconda3/envs/hero/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.wait_for_function: Timeout 30000ms exceeded.
```

**Comment by aldro61** [comment]
I was able to reproduce. Not sure what is causing this. Will look into it asap.

**Comment by aldro61** [comment]
@jardinetsouffleton this issue seems to be limited to list pages. Inspecting the js console, it looks like there is an issue with the javascript that checks if the page load is complete. This requires further investigation to understand what changed in the pages for this issue to surface.

![Screenshot 2024-11-13 at 10 21 00 AM](https://github.com/user-attachments/assets/1b6502be-061e-4da0-a427-996221577f85)

**Comment by aldro61** [comment]
@dangne We were able to track down the issue to an update that was made to playwright. We are still figuring out how to fix the issue, but in the meantime, downgrading to `pip install playwright==1.44.0` should fix it (not that you will need Python <= 3.12).

Can you please give it a shot and let us know?

**Comment by dangne** [comment]
Hi, everything ran smoothly this time! However, for 2 out of 3 tasks, the rewards did not equal 1. Is this a bug?

**Comment by aldro61** [comment]
Glad it ran this time!

Would you be able to tell me which tasks these were?

We validated all the tasks in the benchmark but this could be due to another playwright glitch.

**Comment by Nid989** [comment]
I have been trying to run the `workarena-install` command for a while but been facing the same issue again and again!

```bash
Instance: https://dev280094.service-now.com
Previous installation: never


INFO:root:URL login enabled.
INFO:root:Setting default home page
INFO:root:Guided tours disabled.
INFO:root:Analytics popups disabled.
INFO:root:Welcome help popup disabled.
INFO:root:Installing custom UI themes...
INFO:root:Uploading update set...
INFO:root:Applying update set...
INFO:root:An error occurred. Retrying...
INFO:root:URL login enabled.
INFO:root:Setting default home page
INFO:root:Guided tours disabled.
INFO:root:Analytics popups disabled.
INFO:root:Welcome help popup disabled.
INFO:root:Installing custom UI themes...
INFO:root:Uploading update set...
INFO:root:Applying update set...
INFO:root:An error occurred. Retrying...
INFO:root:URL login enabled.
INFO:root:Setting default home page
INFO:root:Guided tours disabled.
INFO:root:Analytics popups disabled.
INFO:root:Welcome help popup disabled.
INFO:root:Installing custom UI themes...
INFO:root:Uploading update set...
INFO:root:Applying update set...
INFO:root:... WorkArena UI Themes
INFO:root:Setting default UI theme
INFO:root:Wiping all system admin preferences
INFO:root:... Deleting all preferences
INFO:root:...... deleting menu.08771d0cc0a8016401f604303b94b999.expanded
INFO:root:...... deleting sys_update_set
INFO:root:...... deleting glide.ui.polaris.theme.variant
INFO:root:...... deleting updateSetForScopeglobal
INFO:root:Patching reports with date filter...
INFO:root:Disabling report Unique Out of Policy Spoke Integration Transactions 06b188ed0b41330024f8ae9b37673a41 because it uses time filters...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Keeping report Exempt Tables 095fc46153da101045b7ddeeff7b1256 (columns: ['sys_created_on'])...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Keeping report Subscriptions - PA 38125ba2eb022100b8f326115206fef1 (columns: ['sys_created_on'])...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Disabling report Unique Out of Policy Protocol Integration Transactions 6bbceba90b81330024f8ae9b37673afd because it uses time filters...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Keeping report Grandfathered Tables 787fe861531e101045b7ddeeff7b129b (columns: ['sys_created_on'])...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Disabling report Unique Application Users 8c6946006713020012f2575027415a95 because it uses time filters...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Keeping report Custom Applications by Subscription a2ac7b09531a101045b7ddeeff7b12af (columns: ['sys_created_on'])...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Disabling report Google Map Usage By Month b0cd8872c322210066523b251eba8fa2 because it uses time filters...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Keeping report Custom Application Subscriptions ba776c9953f6101045b7ddeeff7b12b7 (columns: ['sys_created_on'])...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Keeping report Global Tables Without Applications c2737305531a101045b7ddeeff7b122c (columns: ['sys_created_on'])...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Disabling report Usage of Custom Applications cafd83021f3121006d691b220e8b701f because it uses time filters...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Keeping report Unsubscribed plugins dc3458319f2022001526317f842e7078 (columns: ['sys_created_on'])...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Disabling report Expired Subscriptions e0929ba2eb022100b8f326115206fef9 because it uses time filters...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Discarding report Custom Tables by Subscription e29b00525332101045b7ddeeff7b128e...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Disabling report Unique Out-of-Policy Users f94b0a006713020012f2575027415ab2 because it uses time filters...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:Keeping report Unsubscribed Usage ffe6db02734010102f1a46162ff6a77e (columns: ['sys_created_on'])...
INFO:root:...failed to patch report. Attempting delete...
ERROR:root:...... could not delete.
INFO:root:All workflows are installed properly.
INFO:root:Knowledge base General Knowledge is already installed.
INFO:root:Knowledge base Company Protocols is corrupt. Reinstalling...
INFO:root:Knowledge base Company Protocols: deleting knowledge base content
INFO:root:Knowledge base Company Protocols: archiving knowledge base
INFO:root:Installing knowledge base Company Protocols...
INFO:root:... creating knowledge base Company Protocols
INFO:root:... Knowledge Base Company Protocols uploading article 1/11
INFO:root:... Knowledge Base Company Protocols uploading article 2/11
INFO:root:... Knowledge Base Company Protocols uploading article 3/11
INFO:root:... Knowledge Base Company Protocols uploading article 4/11
INFO:root:... Knowledge Base Company Protocols uploading article 5/11
INFO:root:... Knowledge Base Company Protocols uploading article 6/11
INFO:root:... Knowledge Base Company Protocols uploading article 7/11
INFO:root:... Knowledge Base Company Protocols uploading article 8/11
INFO:root:... Knowledge Base Company Protocols uploading article 9/11
INFO:root:... Knowledge Base Company Protocols uploading article 10/11
INFO:root:... Knowledge Base Company Protocols uploading article 11/11
INFO:root:Knowledge base Company Protocols installation succeeded.
INFO:root:... Creating a new user account to validate form fields
INFO:root:Setting up form fields for create_change_request...
INFO:root:Checking for new user preferences for create_change_request form fields
INFO:root:Generalizing new settings to all users for create_change_request form fields
INFO:root:Validating form fields for create_change_request...
INFO:root:All fields properly displayed for /now/nav/ui/classic/params/target/change_request.do.
INFO:root:Setting up form fields for create_incident...
INFO:root:Checking for new user preferences for create_incident form fields
INFO:root:Validating form fields for create_incident...
INFO:root:All fields properly displayed for /now/nav/ui/classic/params/target/incident.do.
INFO:root:Setting up form fields for create_hardware...
INFO:root:Checking for new user preferences for create_hardware form fields
INFO:root:Validating form fields for create_hardware...
INFO:root:All fields properly displayed for /now/nav/ui/classic/params/target/alm_hardware.do.
INFO:root:Setting up form fields for create_problem...
INFO:root:Checking for new user preferences for create_problem form fields
INFO:root:Validating form fields for create_problem...
INFO:root:All fields properly displayed for /now/nav/ui/classic/params/target/problem.do.
INFO:root:Setting up form fields for create_user...
INFO:root:Checking for new user preferences for create_user form fields
INFO:root:Validating form fields for create_user...
INFO:root:All fields properly displayed for /now/nav/ui/classic/params/target/sys_user.do.
INFO:root:Setting up form fields for create_request_item...
INFO:root:Checking for new user preferences for create_request_item form fields
INFO:root:Validating form fields for create_request_item...
INFO:root:All fields properly displayed for /now/nav/ui/classic/params/target/sc_req_item.do.
INFO:root:... Deleting the test user account
INFO:root:All form fields properly displayed.
INFO:root:Setting up visible list columns...
INFO:root:... Creating a new user account to validate list columns
INFO:root:... Setting up default view for list alm_asset
INFO:root:...... Fetching default view for list alm_asset...
INFO:root:...... Fetching existing columns for default view of list alm_asset...
INFO:root:...... Deleting existing columns for default view of list alm_asset...
INFO:root:...... Adding expected columns to default view of list alm_asset...
INFO:root:......... asset_tag
INFO:root:......... model.display_name
INFO:root:......... model_category
INFO:root:......... sys_class_name
INFO:root:......... assigned_to
INFO:root:......... location
INFO:root:......... company
INFO:root:......... department
INFO:root:......... install_status
INFO:root:......... warranty_expiration
INFO:root:...... Done.
Traceback (most recent call last):
  File "/Users/nidhirbhavsar/.pyenv/versions/workarena_env/bin/workarena-install", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/browsergym/workarena/install.py", line 1075, in main
    setup()
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/browsergym/workarena/install.py", line 1039, in setup
    setup_list_columns()
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/browsergym/workarena/install.py", line 627, in setup_list_columns
    assert check_all_columns_displayed(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/browsergym/workarena/install.py", line 556, in check_all_columns_displayed
    visible_columns = set(page.evaluate(f"{js_selector}.fields").split(","))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 8518, in evaluate
    self._sync(
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/playwright/_impl/_page.py", line 467, in evaluate
    return await self._main_frame.evaluate(expression, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 278, in evaluate
    await self._channel.send(
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nidhirbhavsar/.pyenv/versions/3.12.0/envs/workarena_env/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.evaluate: TypeError: Cannot read properties of undefined (reading 'fields')
    at eval (eval at evaluate (:234:30), <anonymous>:1:38)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:234:30)
    at UtilityScript.<anonymous> (<anonymous>:1:44)```
    
Any ideas for troubleshooting this?

**Comment by Nid989** [comment]
> @dangne We were able to track down the issue to an update that was made to playwright. We are still figuring out how to fix the issue, but in the meantime, downgrading to `pip install playwright==1.44.0` should fix it (note that you will need Python <= 3.12).
> 
> Can you please give it a shot and let us know?

Has there been any fixes for this lately? I encountered the same issue, however, my system crashes with `playwright=1.44.0`. Had the same issue with the Webarena as well in the past and nothing except `playwright>=1.47.0 w/ python3.12` works on my machine (strange right?!)

**Comment by yeonjooooni** [comment]
Same here! I've tried 
1) python 3.13 + playwright 1.49.0
2) python 3.12 + playwright 1.44.0
3) python 3.12 + playwright 1.47.0
but none of them work (with the same error message).

**Comment by Arcturyus** [comment]
I have exactly the same problem when launching something on WorkArena.
I have tried : 
      python 3.12 + playwright 1.49.0 ⛔️
      python 3.12 + playwright 1.44.0 ⛔️
      python 3.12 + playwright 1.47.0 ⛔️
Nothing work do you have an other idea anyone ?

**Comment by jardinetsouffleton** [comment]
Hi @Arcturyus ! What OS are you running on? I noticed similar issues when running in Ubuntu 24.04, but things worked fine in 22.04

**Comment by Arcturyus** [comment]
Yes i am on Ubuntu 24.04

**Comment by 5456es** [comment]
met similar problems.... Update my info later and wish for some help

**Comment by aldro61** [comment]
Closing this issue for now as this seems like a Playwright issue (see above thread and #57). Please make individual issues if further problems persist.
